apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-01
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1000Mi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: pv-test-01
  nfs:
    server: 172.31.3.236
    path: /tmp/k8spv
